/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davidzaffery' at '1/5/16 7:04 PM' with Gradle 2.8
 *
 * @author davidzaffery, @date 1/5/16 7:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
